name: Run tests

on:
  push:
    branches:
      - trunk
    paths:
      - "ci/**"
      - ".github/workflows/tests.yml"
  pull_request:
    branches:
      - trunk
    paths:
      - "ci/**"
      - ".github/workflows/tests.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Runs the tests
    steps:
      - name: Check out source code
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          cache: npm
          node-version: lts/*
          cache-dependency-path: ci/package-lock.json

      - name: Install dependencies and run tests
        run: npm cit
        working-directory: ci
