name: Update versioned external dependencies

on:
  workflow_dispatch:
  schedule:
    # Runs every 0th minute of every hour (once per hour)
    - cron:  '0 * * * *'

permissions: write-all

jobs:
  update-jetpack:
    runs-on: ubuntu-latest
    name: A job to update Jetpack, Parse.ly and others
    steps:
      - name: Check out source code
        uses: actions/checkout@v3.0.2
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          cache: npm
          node-version: lts/*
          cache-dependency-path: ci/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ci

      - name: Run update
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          LOBBY_VIP_TOKEN: ${{ secrets.LOBBY_VIP_TOKEN }}
        run: node ./ci/update-deps.js
